#!/bin/bash

echo "Copying source files..."
cp $(git rev-parse --show-toplevel)/terminal/src/.Xresources ~/.Xresources
cp $(git rev-parse --show-toplevel)/terminal/src/.tmux.conf ~/.tmux.conf
echo "Registering ~/.Xresources"
xrdb ~/.Xresources
echo "Done copying."
echo ""
