#!/bin/bash

echo "Checking XTerm dependency..."
if [ "$(which xterm)" = "xterm not found" ]; then
    echo "XTerm not found. Installing XTerm..."
    sudo apt install xterm
    echo "Done installing XTerm."
else
    echo "XTerm found."
fi

echo "Checking xrdb dependency..."
if [ "$(which xrdb)" = "xrdb not found" ]; then
    echo "xrdb not found. Installing x11-xserver-utils (contains xrdb)..."
    sudo apt install x11-xserver-utils
    echo "Done installing xrdb."
else
    echo "Xrdb found."
fi

echo "Checking tmux dependency..."
if [ "$(which tmux)" = "tmux not found" ]; then
    echo "tmux not found. Installing tmux..."
    sudo apt install tmux
    echo "Done installing tmux."
else
    echo "Tmux found."
fi

echo "Checking Roboto font dependency..."
if [[ $(apt list --installed 2>&1 | grep fonts-roboto) == *"fonts-roboto"* ]]; then
    echo "Roboto found."
else
    echo "Roboto font not found. Installing font..."
    sudo apt install fonts-roboto
    echo "Done installing font."
fi

echo ""
